### ISSUE TITLE
Hello! 

### ISSUE THREAD

**Issue by radudangratian** [caspernikus/SwiftyConnect#1]
These is the logo that we talked about on discord. Below, in the download like, you will have all the files that you need.With various color and dimension versions.
![swifty](https://user-images.githubusercontent.com/34451833/37863934-81a7ab3e-2f6f-11e8-9663-520bdde7ed6a.jpg)

Download link:
https://drive.google.com/open?id=1aMKLRsp_T3auKB9MgmCSoSojtTWlIIJ9

**Comment by caspernikus** [comment]
@radudangratian Thanks for your contribution :) I am using the logo from now on !
